### ISSUE TITLE
Question about these sensors

### ISSUE THREAD

**Issue by trogmaniac** [morcibacsi/esp32_rmt_chinese_parking_aid#1]
I'd like to connect these sensors directly to an ESP, do you know how they work? I couldn't find anything about it.

**Comment by morcibacsi** [comment]
A quick google search revealed this: https://hardware-rebirth.blogspot.com/2013/07/hacking-chinese-parking-assist-digging.html
Maybe it is a starting point.

**Comment by trogmaniac** [comment]
Thanks, but the sensors only have 2 pins.
